sudo: false

language: php

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest BUILD=git WP_CLI_BIN_DIR=''
    - php: 5.6
      env: WP_VERSION=3.7.11
    - php: 5.3
      env: WP_VERSION=3.7.11 DEPLOY_BRANCH=master

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
      composer global require "phpunit/phpunit=4.8.*"
    else
      composer global require "phpunit/phpunit=5.7.*"
    fi
  - ./ci/prepare.sh

script:
  - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - ./ci/test.sh

after_success: ./ci/deploy.sh

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
